//! GPU-accelerated wide contact solver (G7) — `gpu` feature only.
//!
//! Offloads single-point contact constraint solving to the GPU through wgpu
//! compute shaders. Each workgroup (4 invocations) processes one wide batch
//! of up to 4 single-point contacts — the same batching strategy as the CPU
//! SIMD-wide path (`WideBatch`), but running on the GPU.
//!
//! # Rust-authored shader (no hand-written WGSL)
//!
//! Following the engine-wide CPU↔GPU idea (IDEAS.md #4), the compute shader
//! is written in Rust and translated to WGSL at compile time:
//!
//! - `GpuBodyState` / `GpuBatch` carry `#[derive(WgslStruct)]`: the WGSL
//!   struct declarations are generated from the Rust field lists, and the
//!   derive emits compile-time `offset_of!`/`size_of` assertions that the
//!   `repr(C)` layout matches WGSL alignment rules (vec3 fields must be
//!   padded explicitly — WGSL aligns `vec3<f32>` to 16 bytes). The Rust
//!   structs are the single source of truth for the buffer layout.
//! - `contact_solver` is a `#[gpu_pipeline(...)]` function whose body is the
//!   compute entry point, written in the kernel DSL; the macro generates
//!   the bindings, built-in parameters and `fn main` around it.
//!
//! The assembled source is validated by naga in tests (no device required)
//! and executed against a software adapter (`gpu_solver_*` tests).
//!
//! # Hybrid model
//!
//! Multi-point (block-LCP) manifolds stay on the CPU island path. The GPU
//! and CPU pass are NOT interleaved at Gauss-Seidel granularity — they run
//! sequentially per iteration. This is a Jacobi/GS hybrid that converges
//! slightly differently from the pure CPU path. Consequently the GPU path
//! is NOT bit-identical to the CPU solver. It is off by default and intended
//! for visual-scale scenes where the Strong-Confluence CPU path is adequate
//! for deterministic simulation and the GPU accelerates the visual bulk.

use glam::Vec3;
use ornis_macros::{WgslStruct, gpu_pipeline};
use std::sync::Arc;

use crate::body::RigidBody;
use crate::engine::{Manifold, ManifoldState};
use bytemuck::Zeroable;

// ---------------------------------------------------------------------------
// Buffer strides (verified against the WGSL layout by WgslStruct)
// ---------------------------------------------------------------------------

/// Number of bytes per GPU body state. The value and the per-field offsets
/// are checked against the generated WGSL layout at compile time.
const GPU_BODY_STRIDE: u64 = std::mem::size_of::<GpuBodyState>() as u64;

/// Number of bytes per GPU batch (see `GpuBatch`; same compile-time check).
const GPU_BATCH_STRIDE: u64 = std::mem::size_of::<GpuBatch>() as u64;

// ---------------------------------------------------------------------------
// GPU body state (32 bytes; WGSL declaration generated by WgslStruct)
// ---------------------------------------------------------------------------

/// GPU copy of the solver-relevant body state: linear + angular velocity.
///
/// The explicit `_pad_*` fields mirror WGSL's 16-byte `vec3<f32>` alignment;
/// the WGSL struct declaration is generated from this layout.
#[repr(C, align(16))]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable, WgslStruct)]
struct GpuBodyState {
    velocity: [f32; 3],
    _pad_v: f32,
    angular: [f32; 3],
    _pad_w: f32,
}

impl GpuBodyState {
    fn from_body(b: &RigidBody) -> Self {
        Self {
            velocity: b.velocity.to_array(),
            angular: b.angular_velocity.to_array(),
            _pad_v: 0.0,
            _pad_w: 0.0,
        }
    }

    fn write_to_body(&self, b: &mut RigidBody) {
        b.velocity = Vec3::from_array(self.velocity);
        b.angular_velocity = Vec3::from_array(self.angular);
    }
}

// ---------------------------------------------------------------------------
// GPU batch (SoA, 4 lanes; WGSL declaration generated by WgslStruct)
// ---------------------------------------------------------------------------

#[repr(C, align(16))]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable, WgslStruct)]
pub(crate) struct GpuBatch {
    // Geometry: SoA layout, 4 lanes each → [f32; 4]
    nx: [f32; 4],
    ny: [f32; 4],
    nz: [f32; 4],
    rax: [f32; 4],
    ray: [f32; 4],
    raz: [f32; 4],
    rbx: [f32; 4],
    rby: [f32; 4],
    rbz: [f32; 4],
    ra_nx: [f32; 4],
    ra_ny: [f32; 4],
    ra_nz: [f32; 4],
    rb_nx: [f32; 4],
    rb_ny: [f32; 4],
    rb_nz: [f32; 4],
    t1x: [f32; 4],
    t1y: [f32; 4],
    t1z: [f32; 4],
    t2x: [f32; 4],
    t2y: [f32; 4],
    t2z: [f32; 4],
    ra_t1x: [f32; 4],
    ra_t1y: [f32; 4],
    ra_t1z: [f32; 4],
    rb_t1x: [f32; 4],
    rb_t1y: [f32; 4],
    rb_t1z: [f32; 4],
    ra_t2x: [f32; 4],
    ra_t2y: [f32; 4],
    ra_t2z: [f32; 4],
    rb_t2x: [f32; 4],
    rb_t2y: [f32; 4],
    rb_t2z: [f32; 4],
    // Scalar constants per lane
    inv_ma: [f32; 4],
    inv_mb: [f32; 4],
    total_inv: [f32; 4],
    inv_k_n: [f32; 4],
    inv_k_t1: [f32; 4],
    inv_k_t2: [f32; 4],
    // Linear application factors: n * inv_mass
    apply_n_ax: [f32; 4],
    apply_n_ay: [f32; 4],
    apply_n_az: [f32; 4],
    apply_n_bx: [f32; 4],
    apply_n_by: [f32; 4],
    apply_n_bz: [f32; 4],
    // Angular application factors: I⁻¹_world · (ra×n)  (precomputed)
    apply_w_ax: [f32; 4],
    apply_w_ay: [f32; 4],
    apply_w_az: [f32; 4],
    apply_w_bx: [f32; 4],
    apply_w_by: [f32; 4],
    apply_w_bz: [f32; 4],
    // World-space inverse inertia matrix rows (3 rows × 2 bodies)
    w_a00: [f32; 4],
    w_a01: [f32; 4],
    w_a02: [f32; 4],
    w_a10: [f32; 4],
    w_a11: [f32; 4],
    w_a12: [f32; 4],
    w_a20: [f32; 4],
    w_a21: [f32; 4],
    w_a22: [f32; 4],
    w_b00: [f32; 4],
    w_b01: [f32; 4],
    w_b02: [f32; 4],
    w_b10: [f32; 4],
    w_b11: [f32; 4],
    w_b12: [f32; 4],
    w_b20: [f32; 4],
    w_b21: [f32; 4],
    w_b22: [f32; 4],
    // Restitution bias, speculative target, friction coeff
    bias: [f32; 4],
    // `target` is a reserved WGSL keyword — the member is named `spec_target`.
    spec_target: [f32; 4],
    mu: [f32; 4],
    // Body indices
    body_a: [u32; 4],
    body_b: [u32; 4],
    // Accumulators (read-write on GPU)
    acc: [f32; 4],
    acc_f1: [f32; 4],
    acc_f2: [f32; 4],
    // Active lane count
    count: u32,
    // Explicit tail padding: keeps the struct a multiple of its 16-byte
    // alignment (WGSL stride) without implicit padding, which `Pod` rejects.
    _pad0: u32,
    _pad1: u32,
    _pad2: u32,
}

/// One lane's worth of CPU-side contact data for `GpuBatch::fill_lane`
/// (mirrors the WGSL batch layout: one scalar per field).
struct LaneInput<'a> {
    lane: usize,
    n: Vec3,
    ra: Vec3,
    rb: Vec3,
    target: f32,
    mu: f32,
    bias: f32,
    acc_in: f32,
    a: &'a RigidBody,
    ba_idx: u32,
    b: &'a RigidBody,
    bb_idx: u32,
}

impl GpuBatch {
    fn zero() -> Self {
        Self::zeroed()
    }

    /// Fill one lane from CPU-side contact data.
    /// The per-lane scalars are packed into `LaneInput` (which mirrors the
    /// WGSL batch layout: one scalar per field) to stay within the structural
    /// gate's argument-count limit.
    fn fill_lane(&mut self, input: LaneInput<'_>) {
        let LaneInput {
            lane,
            n,
            ra,
            rb,
            target,
            mu,
            bias,
            acc_in,
            a,
            ba_idx,
            b,
            bb_idx,
        } = input;
        let l3 = |x: &mut [f32; 4], y: &mut [f32; 4], z: &mut [f32; 4], v: Vec3| {
            x[lane] = v.x;
            y[lane] = v.y;
            z[lane] = v.z;
        };

        l3(&mut self.nx, &mut self.ny, &mut self.nz, n);
        l3(&mut self.rax, &mut self.ray, &mut self.raz, ra);
        l3(&mut self.rbx, &mut self.rby, &mut self.rbz, rb);
        self.spec_target[lane] = target;
        self.mu[lane] = mu;
        self.bias[lane] = bias;
        self.acc[lane] = acc_in;
        self.body_a[lane] = ba_idx;
        self.body_b[lane] = bb_idx;
        self.inv_ma[lane] = a.inv_mass;
        self.inv_mb[lane] = b.inv_mass;
        self.total_inv[lane] = a.inv_mass + b.inv_mass;

        // Precompute cross products.
        let ra_n = ra.cross(n);
        let rb_n = rb.cross(n);
        l3(&mut self.ra_nx, &mut self.ra_ny, &mut self.ra_nz, ra_n);
        l3(&mut self.rb_nx, &mut self.rb_ny, &mut self.rb_nz, rb_n);

        // Tangent basis.
        let t1 = tangent_basis(n);
        let t2 = t1.cross(n);
        l3(&mut self.t1x, &mut self.t1y, &mut self.t1z, t1);
        l3(&mut self.t2x, &mut self.t2y, &mut self.t2z, t2);
        l3(
            &mut self.ra_t1x,
            &mut self.ra_t1y,
            &mut self.ra_t1z,
            ra.cross(t1),
        );
        l3(
            &mut self.rb_t1x,
            &mut self.rb_t1y,
            &mut self.rb_t1z,
            rb.cross(t1),
        );
        l3(
            &mut self.ra_t2x,
            &mut self.ra_t2y,
            &mut self.ra_t2z,
            ra.cross(t2),
        );
        l3(
            &mut self.rb_t2x,
            &mut self.rb_t2y,
            &mut self.rb_t2z,
            rb.cross(t2),
        );

        // World-space inverse inertia matrix rows + application factors.
        let wa = world_inertia_matrix(a.orientation, a.inertia);
        let wb = world_inertia_matrix(b.orientation, b.inertia);
        let set_mat = |m: &[Vec3; 3], dest: &mut [&mut [f32; 4]; 9]| {
            for r in 0..3 {
                dest[r * 3][lane] = m[r].x;
                dest[r * 3 + 1][lane] = m[r].y;
                dest[r * 3 + 2][lane] = m[r].z;
            }
        };
        set_mat(
            &wa,
            &mut [
                &mut self.w_a00,
                &mut self.w_a01,
                &mut self.w_a02,
                &mut self.w_a10,
                &mut self.w_a11,
                &mut self.w_a12,
                &mut self.w_a20,
                &mut self.w_a21,
                &mut self.w_a22,
            ],
        );
        set_mat(
            &wb,
            &mut [
                &mut self.w_b00,
                &mut self.w_b01,
                &mut self.w_b02,
                &mut self.w_b10,
                &mut self.w_b11,
                &mut self.w_b12,
                &mut self.w_b20,
                &mut self.w_b21,
                &mut self.w_b22,
            ],
        );

        // Application factors.
        l3(
            &mut self.apply_n_ax,
            &mut self.apply_n_ay,
            &mut self.apply_n_az,
            n * a.inv_mass,
        );
        l3(
            &mut self.apply_n_bx,
            &mut self.apply_n_by,
            &mut self.apply_n_bz,
            n * b.inv_mass,
        );
        l3(
            &mut self.apply_w_ax,
            &mut self.apply_w_ay,
            &mut self.apply_w_az,
            matvec(&wa, ra_n),
        );
        l3(
            &mut self.apply_w_bx,
            &mut self.apply_w_by,
            &mut self.apply_w_bz,
            matvec(&wb, rb_n),
        );

        // Effective stiffness inverses.
        let total = a.inv_mass + b.inv_mass;
        let k_n = total + ra_n.dot(matvec(&wa, ra_n)) + rb_n.dot(matvec(&wb, rb_n));
        let k_t1 = total
            + ra.cross(t1).dot(matvec(&wa, ra.cross(t1)))
            + rb.cross(t1).dot(matvec(&wb, rb.cross(t1)));
        let k_t2 = total
            + ra.cross(t2).dot(matvec(&wa, ra.cross(t2)))
            + rb.cross(t2).dot(matvec(&wb, rb.cross(t2)));
        self.inv_k_n[lane] = if k_n >= 1e-10 { 1.0 / k_n } else { 0.0 };
        self.inv_k_t1[lane] = if k_t1 >= 1e-10 { 1.0 / k_t1 } else { 0.0 };
        self.inv_k_t2[lane] = if k_t2 >= 1e-10 { 1.0 / k_t2 } else { 0.0 };
    }
}

#[inline]
fn tangent_basis(n: Vec3) -> Vec3 {
    let axis = if n.x.abs() < 0.9 { Vec3::X } else { Vec3::Y };
    n.cross(axis).normalize_or(Vec3::Z)
}

/// World inverse inertia as `[row0, row1, row2]` (3 Vec3 columns → row-major).
fn world_inertia_matrix(rot: glam::Quat, inertia: Vec3) -> [Vec3; 3] {
    let inv = Vec3::new(
        if inertia.x > 0.0 {
            1.0 / inertia.x
        } else {
            0.0
        },
        if inertia.y > 0.0 {
            1.0 / inertia.y
        } else {
            0.0
        },
        if inertia.z > 0.0 {
            1.0 / inertia.z
        } else {
            0.0
        },
    );
    let m = glam::Mat3::from_quat(rot);
    let col_x = m.x_axis * inv.x;
    let col_y = m.y_axis * inv.y;
    let col_z = m.z_axis * inv.z;
    [
        m.x_axis * col_x.x + m.y_axis * col_y.x + m.z_axis * col_z.x,
        m.x_axis * col_x.y + m.y_axis * col_y.y + m.z_axis * col_z.y,
        m.x_axis * col_x.z + m.y_axis * col_y.z + m.z_axis * col_z.z,
    ]
}

#[inline]
fn matvec(m: &[Vec3; 3], v: Vec3) -> Vec3 {
    Vec3::new(m[0].dot(v), m[1].dot(v), m[2].dot(v))
}

// ---------------------------------------------------------------------------
// Compute shader — written in Rust, translated to WGSL by #[gpu_pipeline]
// ---------------------------------------------------------------------------

/// One iteration of the wide contact solver for a single batch.
///
/// The body of this function is the WGSL compute entry point (kernel DSL):
/// the bindings below are in scope as storage/uniform variables and `gid`/
/// `lid` are the built-in workgroup parameters. All per-lane writes to
/// `batch_buf` accumulators go through the full buffer path so that they
/// persist across dispatches (the `let b = ...` copy is read-only).
//
// qual:allow(abc) — kernel-DSL body: every statement is translated
// verbatim into the WGSL compute shader by #[gpu_pipeline], which embeds
// ONLY this function's body into `fn main`. Extracting helpers would emit
// calls to functions that do not exist in the shader; splitting requires a
// macro-level helper-inclusion feature, not a local edit.
#[gpu_pipeline(
    workgroup_size = 4,
    storage(body_buf: [GpuBodyState; 64], read_write),
    storage(batch_buf: [GpuBatch; 64], read_write),
    uniform(params: [u32; 4]),
    builtin(gid: workgroup_id, lid: local_invocation_id),
)]
fn contact_solver() {
    // qual:allow(abc) — kernel-DSL body: every statement is translated
    // verbatim into the WGSL compute shader by #[gpu_pipeline], which embeds
    // ONLY this function's body into `fn main`. Extracting helpers would emit
    // calls to functions that do not exist in the shader; splitting requires a
    // macro-level helper-inclusion feature, not a local edit.
    let b = batch_buf[gid.x];
    let l = lid.x;
    if l >= b.count {
        return;
    }
    let iter = params.x;
    let total = params.y;
    let allow_rest = params.z;

    // Gather body velocities.
    let mut ba = body_buf[b.body_a[l]];
    let mut bb = body_buf[b.body_b[l]];
    let va = ba.velocity;
    let wa = ba.angular;
    let vb = bb.velocity;
    let wb = bb.angular;

    let n = vec3(b.nx[l], b.ny[l], b.nz[l]);
    let ra = vec3(b.rax[l], b.ray[l], b.raz[l]);
    let rb = vec3(b.rbx[l], b.rby[l], b.rbz[l]);
    let inv_ma = b.inv_ma[l];
    let inv_mb = b.inv_mb[l];
    let inv_k = b.inv_k_n[l];
    let spec_target = b.spec_target[l];
    let mut acc = batch_buf[gid.x].acc[l];

    // Normal impulse.
    let rel = (vb + cross(wb, rb)) - (va + cross(wa, ra));
    let vn = dot(rel, n);
    let lambda = (spec_target - vn) * inv_k;
    let new_acc = max(acc + lambda, 0.0);
    let delta = new_acc - acc;
    acc = new_acc;

    if abs(delta) > 1e-12 {
        ba.velocity -= delta * vec3(b.apply_n_ax[l], b.apply_n_ay[l], b.apply_n_az[l]);
        bb.velocity += delta * vec3(b.apply_n_bx[l], b.apply_n_by[l], b.apply_n_bz[l]);
        ba.angular -= delta * vec3(b.apply_w_ax[l], b.apply_w_ay[l], b.apply_w_az[l]);
        bb.angular += delta * vec3(b.apply_w_bx[l], b.apply_w_by[l], b.apply_w_bz[l]);
    }

    // Friction (remeasure rel after the normal impulse).
    let rel2 = (bb.velocity + cross(bb.angular, rb)) - (ba.velocity + cross(ba.angular, ra));
    let max_f = b.mu[l] * acc;
    let t1 = vec3(b.t1x[l], b.t1y[l], b.t1z[l]);
    let t2 = vec3(b.t2x[l], b.t2y[l], b.t2z[l]);
    let mut f_imp = vec3(0.0);

    // Axis 1.
    if b.inv_k_t1[l] > 0.0 {
        let vt1 = dot(rel2, t1);
        let new_t1 = batch_buf[gid.x].acc_f1[l] - vt1 * b.inv_k_t1[l];
        let len1 = sqrt(new_t1 * new_t1 + batch_buf[gid.x].acc_f2[l] * batch_buf[gid.x].acc_f2[l]);
        let new_t1c = select(
            new_t1,
            new_t1 * (max_f / len1),
            len1 > max_f && len1 > 1e-12,
        );
        f_imp += t1 * (new_t1c - batch_buf[gid.x].acc_f1[l]);
        batch_buf[gid.x].acc_f1[l] = new_t1c;
    }
    // Axis 2.
    if b.inv_k_t2[l] > 0.0 {
        let vt2 = dot(rel2, t2);
        let new_t2 = batch_buf[gid.x].acc_f2[l] - vt2 * b.inv_k_t2[l];
        let len2 = sqrt(new_t2 * new_t2 + batch_buf[gid.x].acc_f1[l] * batch_buf[gid.x].acc_f1[l]);
        let new_t2c = select(
            new_t2,
            new_t2 * (max_f / len2),
            len2 > max_f && len2 > 1e-12,
        );
        f_imp += t2 * (new_t2c - batch_buf[gid.x].acc_f2[l]);
        batch_buf[gid.x].acc_f2[l] = new_t2c;
    }
    if dot(f_imp, f_imp) > 1e-24 {
        // Angular impulse uses r × f (same convention as the scalar solver:
        // `wa -= W·(ra×f)`, `wb += W·(rb×f)`).
        let ca = cross(ra, f_imp);
        let w_a = vec3(
            dot(vec3(b.w_a00[l], b.w_a01[l], b.w_a02[l]), ca),
            dot(vec3(b.w_a10[l], b.w_a11[l], b.w_a12[l]), ca),
            dot(vec3(b.w_a20[l], b.w_a21[l], b.w_a22[l]), ca),
        );
        let cb = cross(rb, f_imp);
        let w_b = vec3(
            dot(vec3(b.w_b00[l], b.w_b01[l], b.w_b02[l]), cb),
            dot(vec3(b.w_b10[l], b.w_b11[l], b.w_b12[l]), cb),
            dot(vec3(b.w_b20[l], b.w_b21[l], b.w_b22[l]), cb),
        );
        ba.velocity -= f_imp * inv_ma;
        bb.velocity += f_imp * inv_mb;
        ba.angular -= w_a;
        bb.angular += w_b;
    }

    // Restitution (one-shot on the last iteration).
    if allow_rest > 0 && iter == total - 1 {
        let bias = b.bias[l];
        if bias > 0.0 {
            let rel3 =
                (bb.velocity + cross(bb.angular, rb)) - (ba.velocity + cross(ba.angular, ra));
            let vn3 = dot(rel3, n);
            let lr = (bias - vn3) * inv_k;
            if lr > 0.0 {
                ba.velocity -= lr * vec3(b.apply_n_ax[l], b.apply_n_ay[l], b.apply_n_az[l]);
                bb.velocity += lr * vec3(b.apply_n_bx[l], b.apply_n_by[l], b.apply_n_bz[l]);
                ba.angular -= lr * vec3(b.apply_w_ax[l], b.apply_w_ay[l], b.apply_w_az[l]);
                bb.angular += lr * vec3(b.apply_w_bx[l], b.apply_w_by[l], b.apply_w_bz[l]);
            }
        }
    }

    // Write back.
    body_buf[b.body_a[l]].velocity = ba.velocity;
    body_buf[b.body_a[l]].angular = ba.angular;
    body_buf[b.body_b[l]].velocity = bb.velocity;
    body_buf[b.body_b[l]].angular = bb.angular;
    batch_buf[gid.x].acc[l] = acc;
}

/// The complete WGSL source: struct declarations (generated from the Rust
/// layouts) + the compute shader translated from `contact_solver`.
fn contact_solver_wgsl() -> String {
    format!(
        "{}\n{}\n{}",
        GpuBodyState::WGSL_SOURCE,
        GpuBatch::WGSL_SOURCE,
        contact_solver::wgsl_source()
    )
}

// ---------------------------------------------------------------------------
// WGPU contact solver
// ---------------------------------------------------------------------------

/// GPU-accelerated contact solver for single-point manifold batches.
pub struct WgpuContactSolver {
    device: Arc<wgpu::Device>,
    queue: Arc<wgpu::Queue>,
    pipeline: wgpu::ComputePipeline,
    bind_group: wgpu::BindGroup,
    body_buf: wgpu::Buffer,     // read-write body state
    batch_buf: wgpu::Buffer,    // read-write batch data (acc accumulators)
    uniform_buf: wgpu::Buffer,  // params: (iter, total, allow_rest, 0)
    readback_buf: wgpu::Buffer, // staging copy for body download
    max_bodies: usize,
    max_batches: usize,
}

impl WgpuContactSolver {
    /// Create a new GPU solver attached to the given wgpu context.
    /// `max_bodies` and `max_batches` must be large enough for the scene.
    pub fn new(
        device: Arc<wgpu::Device>,
        queue: Arc<wgpu::Queue>,
        max_bodies: usize,
        max_batches: usize,
    ) -> Self {
        let source = contact_solver_wgsl();
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("physics_contact"),
            source: wgpu::ShaderSource::Wgsl(source.into()),
        });

        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("physics_contact_bgl"),
            entries: &[
                // body_buf: read-write storage
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: false },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                // batch_buf: read-write storage (acc accumulators)
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: false },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                // uniform: uniform buffer
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        });
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("physics_contact_layout"),
            bind_group_layouts: &[Some(&bind_group_layout)],
            immediate_size: 0,
        });

        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("physics_contact_pipeline"),
            layout: Some(&pipeline_layout),
            module: &shader,
            entry_point: Some("main"),
            compilation_options: Default::default(),
            cache: None,
        });

        let body_size = max_bodies.next_power_of_two().max(64) as u64 * GPU_BODY_STRIDE;
        let batch_size = max_batches.next_power_of_two().max(64) as u64 * GPU_BATCH_STRIDE;

        let body_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("physics_body_state"),
            size: body_size,
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::COPY_SRC
                | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let batch_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("physics_contact_batches"),
            size: batch_size,
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::COPY_DST
                | wgpu::BufferUsages::COPY_SRC,
            mapped_at_creation: false,
        });
        let uniform_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("physics_contact_uniform"),
            size: 16, // vec4<u32>
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let readback_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("physics_contact_readback"),
            size: body_size,
            usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("physics_contact_bg"),
            layout: &bind_group_layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: body_buf.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: batch_buf.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: uniform_buf.as_entire_binding(),
                },
            ],
        });

        Self {
            device,
            queue,
            pipeline,
            bind_group,
            body_buf,
            batch_buf,
            uniform_buf,
            readback_buf,
            max_bodies,
            max_batches,
        }
    }

    /// Upload body velocities to the GPU buffer.
    pub fn upload_bodies(&self, bodies: &[RigidBody]) {
        let n = bodies.len().min(self.max_bodies);
        let mut data = vec![GpuBodyState::zeroed(); self.max_bodies];
        for (i, b) in bodies.iter().enumerate().take(n) {
            data[i] = GpuBodyState::from_body(b);
        }
        self.queue
            .write_buffer(&self.body_buf, 0, bytemuck::cast_slice(&data));
    }

    /// Download body velocities from the GPU buffer (blocking).
    pub fn download_bodies(&self, bodies: &mut [RigidBody]) {
        let n = bodies.len().min(self.max_bodies);
        let copy_size = self.max_bodies as u64 * GPU_BODY_STRIDE;
        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("physics_download"),
            });
        encoder.copy_buffer_to_buffer(&self.body_buf, 0, &self.readback_buf, 0, copy_size);
        self.queue.submit([encoder.finish()]);
        self.device
            .poll(wgpu::PollType::Wait {
                submission_index: None,
                timeout: None,
            })
            .ok();

        let slice = self.readback_buf.slice(..);
        slice.map_async(wgpu::MapMode::Read, |_| {});
        self.device
            .poll(wgpu::PollType::Wait {
                submission_index: None,
                timeout: None,
            })
            .ok();
        let mapped = slice.get_mapped_range().unwrap();
        let states: &[GpuBodyState] = bytemuck::cast_slice(&mapped);
        for (i, b) in bodies.iter_mut().enumerate().take(n) {
            states[i].write_to_body(b);
        }
        drop(mapped);
        self.readback_buf.unmap();
    }

    /// Upload contact batches to the GPU buffer.
    pub(crate) fn upload_batches(&self, batches: &[GpuBatch]) {
        let n = batches.len().min(self.max_batches);
        let mut data = vec![GpuBatch::zeroed(); self.max_batches];
        for (i, b) in batches.iter().enumerate().take(n) {
            data[i] = *b;
        }
        self.queue
            .write_buffer(&self.batch_buf, 0, bytemuck::cast_slice(&data));
    }

    /// Download accumulated impulses back from the GPU batch buffer.
    pub(crate) fn download_acc(&self, batches: &mut [GpuBatch]) {
        let n = batches.len().min(self.max_batches);
        let copy_size = self.max_batches as u64 * GPU_BATCH_STRIDE;
        let readback = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("physics_acc_readback"),
            size: copy_size,
            usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("physics_acc_dl"),
            });
        encoder.copy_buffer_to_buffer(&self.batch_buf, 0, &readback, 0, copy_size);
        self.queue.submit([encoder.finish()]);
        self.device
            .poll(wgpu::PollType::Wait {
                submission_index: None,
                timeout: None,
            })
            .ok();
        readback.slice(..).map_async(wgpu::MapMode::Read, |_| {});
        self.device
            .poll(wgpu::PollType::Wait {
                submission_index: None,
                timeout: None,
            })
            .ok();
        let mapped = readback.slice(..).get_mapped_range().unwrap();
        let raw: &[u8] = &mapped;
        let gpu_entries: &[GpuBatch] = bytemuck::cast_slice(raw);
        for (i, b) in batches.iter_mut().enumerate().take(n) {
            b.acc = gpu_entries[i].acc;
            b.acc_f1 = gpu_entries[i].acc_f1;
            b.acc_f2 = gpu_entries[i].acc_f2;
        }
        drop(mapped);
        readback.unmap();
    }

    /// Run the GPU contact solver for `iterations` GS iterations plus one
    /// restitution dispatch if `allow_restitution`.
    pub fn solve(&self, num_batches: u32, iterations: u32, allow_restitution: bool) {
        for i in 0..iterations {
            let params = [i, iterations, if allow_restitution { 1 } else { 0 }, 0];
            self.queue
                .write_buffer(&self.uniform_buf, 0, bytemuck::cast_slice(&params));
            let mut encoder = self
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("physics_contact_iter"),
                });
            {
                let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("physics_contact_pass"),
                    timestamp_writes: None,
                });
                cpass.set_pipeline(&self.pipeline);
                cpass.set_bind_group(0, &self.bind_group, &[]);
                cpass.dispatch_workgroups(num_batches, 1, 1);
            }
            self.queue.submit([encoder.finish()]);
            // Barrier between iterations: wait for the previous dispatch.
            self.device
                .poll(wgpu::PollType::Wait {
                    submission_index: None,
                    timeout: None,
                })
                .ok();
        }
    }
}

// ---------------------------------------------------------------------------
// Public API: pack GPU batches from engine data
// ---------------------------------------------------------------------------

/// Pack single-point manifold states into GPU batches.
/// Returns the batches and their count.
pub fn pack_single_point_batches(
    bodies: &[RigidBody],
    states: &[ManifoldState],
    manifolds: &[Manifold],
    single_indices: &[usize], // indices into states
) -> (Vec<GpuBatch>, u32) {
    // Group into batches of ≤4 disjoint contacts (same strategy as
    // build_solver_steps, but using global body indices).
    let mut batches: Vec<GpuBatch> = Vec::new();
    let mut cur = GpuBatch::zero();
    let mut cur_len = 0usize;
    let mut cur_bodies: [usize; 8] = [usize::MAX; 8];
    let mut cur_n = 0usize;

    fn flush_batch(
        batches: &mut Vec<GpuBatch>,
        cur: &mut GpuBatch,
        cur_len: &mut usize,
        cur_bodies: &mut [usize; 8],
        cur_n: &mut usize,
    ) {
        if *cur_len == 0 {
            return;
        }
        cur.count = *cur_len as u32;
        batches.push(*cur);
        *cur = GpuBatch::zero();
        *cur_len = 0;
        *cur_n = 0;
        *cur_bodies = [usize::MAX; 8];
    }

    for &si in single_indices {
        let st = &states[si];
        let m = &manifolds[st.mi];
        let (i, j) = (st.i, st.j);
        let conflicts = cur_bodies[..cur_n].contains(&i) || cur_bodies[..cur_n].contains(&j);
        if cur_len >= 4 || conflicts {
            flush_batch(
                &mut batches,
                &mut cur,
                &mut cur_len,
                &mut cur_bodies,
                &mut cur_n,
            );
        }
        let p = m.points[0].world_point;
        let ra = p - bodies[i].position;
        let rb = p - bodies[j].position;
        cur.fill_lane(LaneInput {
            lane: cur_len,
            n: m.normal,
            ra,
            rb,
            target: st.target[0],
            mu: st.mu,
            bias: st.bias[0],
            acc_in: st.acc[0],
            a: &bodies[i],
            ba_idx: i as u32,
            b: &bodies[j],
            bb_idx: j as u32,
        });
        cur_bodies[cur_n] = i;
        cur_bodies[cur_n + 1] = j;
        cur_n += 2;
        cur_len += 1;
        cur.count = cur_len as u32;
    }
    flush_batch(
        &mut batches,
        &mut cur,
        &mut cur_len,
        &mut cur_bodies,
        &mut cur_n,
    );

    let count = batches.len() as u32;
    (batches, count)
}

/// Write GPU batch accumulated impulses back to the ManifoldState array
/// (for warm-cache persistence).
pub fn write_back_acc(
    states: &mut [ManifoldState],
    single_indices: &[usize],
    batches: &[GpuBatch],
) {
    let mut bi = 0usize;
    let mut lane = 0usize;
    for &si in single_indices {
        if lane >= batches[bi].count as usize {
            bi += 1;
            lane = 0;
        }
        states[si].acc[0] = batches[bi].acc[lane];
        lane += 1;
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::body::RigidBody;
    use crate::engine::{
        BuiltinPhysicsEngine, Manifold, ManifoldPoint, ManifoldState, PhysicsEngine,
    };

    #[test]
    fn gpu_pack_produces_disjoint_batches() {
        let bodies = vec![
            RigidBody::new_sphere(Vec3::ZERO, 0.5, 0.0), // 0: static
            RigidBody::new_sphere(Vec3::new(1.0, 0.0, 0.0), 0.5, 1.0), // 1
            RigidBody::new_sphere(Vec3::new(2.0, 0.0, 0.0), 0.5, 1.0), // 2
            RigidBody::new_sphere(Vec3::new(3.0, 0.0, 0.0), 0.5, 1.0), // 3
            RigidBody::new_sphere(Vec3::new(4.0, 0.0, 0.0), 0.5, 1.0), // 4
        ];
        // Single-point manifold helper
        fn mk_manifold(i: usize, j: usize, n: Vec3, p: Vec3) -> Manifold {
            Manifold {
                body_a: i,
                body_b: j,
                normal: n,
                point_count: 1,
                points: [ManifoldPoint {
                    world_point: p,
                    penetration: 0.01,
                }; 4],
            }
        }
        fn mk_state(i: usize, j: usize) -> ManifoldState {
            ManifoldState {
                mi: 0,
                i,
                j,
                count: 1,
                acc: [0.0; 4],
                acc_friction: [0.0; 4],
                acc_friction2: [0.0; 4],
                bias: [0.0; 4],
                target: [0.0; 4],
                mu: 0.3,
                t1: Vec3::X,
                t2: Vec3::Z,
                la: [Vec3::ZERO; 4],
                lb: [Vec3::ZERO; 4],
                pen0: [0.0; 4],
            }
        }

        // Create contacts (0,1), (0,2) — conflict on 0
        let manifolds = vec![
            mk_manifold(0, 1, Vec3::X, Vec3::ZERO),
            mk_manifold(0, 2, Vec3::X, Vec3::ZERO),
            mk_manifold(3, 4, Vec3::X, Vec3::new(3.5, 0.0, 0.0)),
        ];
        let states: Vec<ManifoldState> = (0..3)
            .map(|i| {
                let m = &manifolds[i];
                mk_state(m.body_a, m.body_b)
            })
            .collect();
        let single_indices: Vec<usize> = (0..3).collect();

        let (batches, count) =
            pack_single_point_batches(&bodies, &states, &manifolds, &single_indices);
        assert_eq!(count, 2, "should form 2 batches: [1, 2] with conflict");
        assert_eq!(
            batches[0].count, 1,
            "first batch only has the non-conflicting contact... wait"
        );
        // Actually with greedy pack: (0,1) starts batch; (0,2) conflicts → flush batch1(1), start batch2 with (0,2); (3,4) clears bodies → adds to batch2.
        // So batch[0].count = 1 (just 0,1), batch[1].count = 2 (0,2 + 3,4).
        assert_eq!(batches[1].count, 2, "second batch has 2 lanes");
    }

    #[test]
    fn layout_stride_matches_struct_size() {
        // The WgslStruct derive asserts per-field offsets and the total size
        // at compile time; the buffer strides must be the same numbers.
        assert_eq!(GPU_BODY_STRIDE, 32);
        assert_eq!(GPU_BATCH_STRIDE, std::mem::size_of::<GpuBatch>() as u64);
        assert_eq!(std::mem::offset_of!(GpuBodyState, velocity), 0);
        assert_eq!(std::mem::offset_of!(GpuBodyState, angular), 16);
    }

    #[test]
    fn generated_wgsl_contains_rust_authored_layouts() {
        let source = contact_solver_wgsl();
        // Struct declarations are generated from the Rust structs...
        assert!(source.contains("struct GpuBodyState"));
        assert!(source.contains("velocity: vec3<f32>"));
        assert!(source.contains("struct GpuBatch"));
        assert!(source.contains("count: u32"));
        // ...and the entry point is translated from the Rust kernel body.
        assert!(source.contains("@compute @workgroup_size(4)"));
        assert!(source.contains("array<GpuBodyState>"));
        assert!(source.contains("fn main("));
        assert!(source.contains("let b = batch_buf[gid.x];"));
        assert!(source.contains("if (l >= b.count) { return; }"));
        assert!(source.contains("batch_buf[gid.x].acc[l] = acc;"));
    }

    #[test]
    fn generated_wgsl_validates_with_naga() {
        let source = contact_solver_wgsl();
        let module = naga::front::wgsl::parse_str(&source)
            .unwrap_or_else(|e| panic!("generated WGSL must parse: {e}"));
        let mut validator = naga::valid::Validator::new(
            naga::valid::ValidationFlags::all(),
            naga::valid::Capabilities::all(),
        );
        validator
            .validate(&module)
            .unwrap_or_else(|e| panic!("generated WGSL must validate: {e}"));
    }

    /// Create a wgpu device/queue for tests. Returns `None` when no adapter
    /// is available (e.g. a machine without GPU drivers) — the device tests
    /// then skip instead of failing.
    fn create_test_device() -> Option<(Arc<wgpu::Device>, Arc<wgpu::Queue>)> {
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::all(),
            flags: wgpu::InstanceFlags::empty(),
            memory_budget_thresholds: Default::default(),
            backend_options: Default::default(),
            display: None,
        });
        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            force_fallback_adapter: false,
            compatible_surface: None,
            apply_limit_buckets: false,
        }))
        .ok()?;
        let (device, queue) = pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
            label: Some("ornis-physics gpu test"),
            required_features: wgpu::Features::empty(),
            required_limits: wgpu::Limits::downlevel_defaults(),
            experimental_features: wgpu::ExperimentalFeatures::disabled(),
            memory_hints: wgpu::MemoryHints::Performance,
            trace: wgpu::Trace::Off,
        }))
        .ok()?;
        Some((Arc::new(device), Arc::new(queue)))
    }

    /// Direct solver-level check: a sphere falling onto a static sphere must
    /// cancel its normal velocity, accumulate the full impulse, and leave the
    /// static body untouched.
    #[test]
    fn gpu_solver_single_contact_matches_analytic() {
        let Some((device, queue)) = create_test_device() else {
            eprintln!("gpu_solver_single_contact_matches_analytic: no wgpu adapter — skipped");
            return;
        };
        let solver = WgpuContactSolver::new(device, queue, 2, 1);

        let a = RigidBody::new_sphere(Vec3::ZERO, 0.5, 0.0); // static
        let mut b = RigidBody::new_sphere(Vec3::new(0.0, 1.0, 0.0), 0.5, 1.0);
        b.velocity = Vec3::new(0.0, -1.0, 0.0);

        let mut batch = GpuBatch::zero();
        batch.fill_lane(LaneInput {
            lane: 0,
            n: Vec3::Y,                    // normal
            ra: Vec3::new(0.0, 0.5, 0.0),  // ra = contact − center a
            rb: Vec3::new(0.0, -0.5, 0.0), // rb = contact − center b
            target: 0.0,                   // target (non-speculative rest)
            mu: 0.0,                       // mu (no friction)
            bias: 0.0,                     // bias (no restitution)
            acc_in: 0.0,                   // acc_in
            a: &a,
            ba_idx: 0,
            b: &b,
            bb_idx: 1,
        });
        batch.count = 1;

        solver.upload_bodies(&[a.clone(), b.clone()]);
        solver.upload_batches(&[batch]);
        solver.solve(1, 8, false);

        let mut out = [a, b];
        solver.download_bodies(&mut out);
        let mut acc_batches = [batch];
        solver.download_acc(&mut acc_batches);

        assert!(
            out[1].velocity.length() < 1e-3,
            "normal velocity must be cancelled, got {:?}",
            out[1].velocity
        );
        assert!(
            (acc_batches[0].acc[0] - 1.0).abs() < 1e-2,
            "accumulated impulse must equal the body mass, got {}",
            acc_batches[0].acc[0]
        );
        assert_eq!(out[0].velocity, Vec3::ZERO, "static body must not move");
        assert_eq!(out[0].angular_velocity, Vec3::ZERO);
        assert!(
            out[1].angular_velocity.length() < 1e-3,
            "no torque expected"
        );
    }

    /// Engine-level check: the same scene run on the CPU and with the GPU
    /// solver attached must settle to the same resting state.
    #[test]
    fn gpu_solver_tracks_cpu_engine() {
        let Some((device, queue)) = create_test_device() else {
            eprintln!("gpu_solver_tracks_cpu_engine: no wgpu adapter — skipped");
            return;
        };
        let solver = WgpuContactSolver::new(device, queue, 16, 64);
        let gravity = Vec3::new(0.0, -9.81, 0.0);

        let mut cpu = BuiltinPhysicsEngine::new(gravity);
        let mut gpu = BuiltinPhysicsEngine::new(gravity);
        for engine in [&mut cpu, &mut gpu] {
            engine.add_body(RigidBody::new_box(
                Vec3::new(0.0, -2.0, 0.0),
                Vec3::new(4.0, 0.5, 4.0),
                0.0,
            ));
            // Vertically aligned stack: with lateral offsets the stack
            // topples chaotically and the Jacobi/GS hybrid (GPU path is not
            // bit-identical to the CPU GS pass) diverges past any tight
            // tolerance — the contract checked here is the settled state of
            // a STABLE stack.
            engine.add_body(RigidBody::new_sphere(Vec3::new(0.0, 0.0, 0.0), 0.5, 1.0));
            engine.add_body(RigidBody::new_sphere(Vec3::new(0.0, 1.2, 0.0), 0.5, 1.0));
            engine.add_body(RigidBody::new_sphere(Vec3::new(0.0, 2.4, 0.0), 0.5, 1.0));
        }
        gpu.set_gpu_solver(solver);

        for _ in 0..60 {
            cpu.step(1.0 / 60.0);
            gpu.step(1.0 / 60.0);
        }

        for i in 0..4 {
            let (bc, bg) = (cpu.get_body(i).unwrap(), gpu.get_body(i).unwrap());
            assert!(
                bc.position.distance(bg.position) < 0.05,
                "body {i} position diverged: cpu {:?} vs gpu {:?}",
                bc.position,
                bg.position
            );
            assert!(
                bc.velocity.distance(bg.velocity) < 0.05,
                "body {i} velocity diverged: cpu {:?} vs gpu {:?}",
                bc.velocity,
                bg.velocity
            );
        }
    }
}
