//! Render the Ornis editor using Blitz (via forks/blitz).
//!
//! This is a standalone example that lives in the Ornis workspace but
//! depends on the Blitz fork via a path dependency.
//!
//! Usage:
//!   cargo run -p ornis-blitz --release -- [width] [height] [output.png]
//!
//! The HTML+CSS is generated by the Ornis editor template.

use std::path::PathBuf;

fn main() {
    let width: u32 = std::env::args()
        .nth(1).and_then(|a| a.parse().ok()).unwrap_or(1920);
    let height: u32 = std::env::args()
        .nth(2).and_then(|a| a.parse().ok()).unwrap_or(1080);
    let out_path = std::env::args()
        .nth(3).map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/tmp/blitz_render.png"));

    // Generate the editor HTML+CSS using Ornis template
    let config = ornis_ui::UnifiedEditorConfig::default();
    let css = ornis_ui::editor_template::EditorTemplate::generate_css_with_theme(&config);
    let html = ornis_ui::editor_template::EditorTemplate::generate_html(&config);

    // Wrap in full HTML document
    let full_html = format!(
        r#"<!DOCTYPE html><html><head><meta charset="utf-8"><style>{css}</style></head><body>{html}</body></html>"#
    );

    println!("Generated {} bytes of HTML+CSS for Ornis editor", full_html.len());

    // Render using Blitz
    use anyrender::ImageRenderer;
    use anyrender_vello::VelloImageRenderer;
    use blitz_dom::DocumentConfig;
    use blitz_html::HtmlDocument;
    use blitz_paint::paint_scene;
    use blitz_traits::shell::{ColorScheme, Viewport};
    use std::sync::Arc;

    let net = Arc::new(blitz_net::Provider::new(None));

    let mut doc = HtmlDocument::from_html(
        &full_html,
        DocumentConfig {
            base_url: None,
            net_provider: Some(Arc::clone(&net) as _),
            viewport: Some(Viewport::new(width, height, 1.0, ColorScheme::Dark)),
            ..Default::default()
        },
    );
    println!("Parsed document");

    // Resolve network resources
    let mut timeout = 1000;
    loop {
        doc.resolve(0.0);
        if net.is_empty() || timeout == 0 { break; }
        timeout -= 1;
    }

    // Compute style + layout
    doc.as_mut().resolve(0.0);
    println!("Resolved layout");

    // GPU render
    let mut renderer = VelloImageRenderer::new(width, height);
    let mut buf = Vec::new();
    renderer.render_to_vec(
        |scene| {
            use anyrender::PaintScene;
            use peniko::{Fill, kurbo::Rect};
            scene.fill(
                Fill::NonZero,
                Default::default(),
                peniko::Color::BLACK,
                Default::default(),
                &Rect::new(0.0, 0.0, width as f64, height as f64),
            );
            paint_scene(scene, doc.as_mut(), 1.0, width, height, 0, 0);
        },
        &mut buf,
    );
    println!("Rendered {}x{} to buffer", width, height);

    // Write PNG
    let mut file = std::fs::File::create(&out_path).unwrap();
    let mut encoder = png::Encoder::new(&mut file, width, height);
    encoder.set_color(png::ColorType::Rgba);
    encoder.set_depth(png::BitDepth::Eight);
    let mut writer = encoder.write_header().unwrap();
    writer.write_image_data(&buf).unwrap();
    writer.finish().unwrap();
    println!("Written to {}", out_path.display());
}
