[package]
name = "ornis-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
wgpu = "29"
bytemuck = { version = "1", features = ["derive"] }
glam = "0.30"
ornis-core = { path = "../core" }
ornis-macros = { path = "../macros" }
serde = { version = "1", features = ["derive"] }
ron = "0.8"

[dev-dependencies]
pollster = "0.3"
png = "0.17"
