[package]
name = "ornis-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
boa_engine = { version = "0.21", optional = true }
html5ever = "0.27"
lightningcss = "1.0.0-alpha.71"
parcel_selectors = "0.28.2"
taffy = { version = "0.12", features = ["grid"] }
vello = { version = "0.9", features = ["wgpu"] }
skrifa = "0.37"
wgpu = "29"
winit = "0.30"
crossbeam-channel = "0.5"
ornis-core = { path = "../core" }
ornis-wgpu-backend = { path = "../wgpu_backend" }
glam = "0.30"
image = "0.25"
serde = { version = "1", features = ["derive"] }
png = "0.17"
cosmic-text = "0.13"

[features]
serialize = ["dep:serde_json"]
js-engine = ["dep:boa_engine"]
default = ["js-engine"]
[dependencies.serde_json]
version = "1"
optional = true

[dev-dependencies]
pollster = "0.3"

[lints]
workspace = true
