//! GPU single-point contact batches: layout, packing and the SI compute kernel.
//!
//! Owns [`GpuBatch`]/[`LaneInput`] (SoA lanes over disjoint bodies, packed by
//! [`pack_single_point_batches`]), the Rust-authored `contact_solver` compute
//! kernel (translated to WGSL by `#[gpu_pipeline]`, helpers stitched from
//! `contact_math`) and the [`contact_solver_wgsl`] source used by the host
//! [`crate::gpu::GpuSequentialImpulse`]. Moved verbatim from `gpu.rs` (phase 3).

use glam::Vec3;
use ornis_macros::{WgslStruct, gpu_pipeline};

use super::GpuBodyState;
use crate::body::RigidBody;
use crate::contact_math::{contact_friction_clamp, contact_normal_step};
use crate::engine::{Manifold, ManifoldState};
use bytemuck::Zeroable;

/// Lanes per GPU contact batch (SoA width; matches `[f32; 4]` fields).
const BATCH_LANES: usize = 4;
/// Body-index scratch capacity while packing a batch (2 bodies × [`BATCH_LANES`]).
const BATCH_BODY_SLOTS: usize = 8;
/// Host-side stiffness floor: below this, `inv_k_*` is treated as zero.
const STIFFNESS_EPS: f32 = 1e-10;
/// Linear DOF / matrix row count for world-inertia packing.
const LINEAR_DOF: usize = 3;
/// Flattened 3×3 inertia matrix element count.
const INERTIA_MAT_ELEMS: usize = LINEAR_DOF * LINEAR_DOF;

// ---------------------------------------------------------------------------
// GPU batch (SoA, 4 lanes; WGSL declaration generated by WgslStruct)
// ---------------------------------------------------------------------------

#[repr(C, align(16))]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable, WgslStruct)]
/// One GPU contact batch: up to 4 single-point lanes over disjoint bodies.
pub struct GpuBatch {
    // Geometry: SoA layout, 4 lanes each → [f32; 4]
    nx: [f32; 4],
    ny: [f32; 4],
    nz: [f32; 4],
    rax: [f32; 4],
    ray: [f32; 4],
    raz: [f32; 4],
    rbx: [f32; 4],
    rby: [f32; 4],
    rbz: [f32; 4],
    ra_nx: [f32; 4],
    ra_ny: [f32; 4],
    ra_nz: [f32; 4],
    rb_nx: [f32; 4],
    rb_ny: [f32; 4],
    rb_nz: [f32; 4],
    t1x: [f32; 4],
    t1y: [f32; 4],
    t1z: [f32; 4],
    t2x: [f32; 4],
    t2y: [f32; 4],
    t2z: [f32; 4],
    ra_t1x: [f32; 4],
    ra_t1y: [f32; 4],
    ra_t1z: [f32; 4],
    rb_t1x: [f32; 4],
    rb_t1y: [f32; 4],
    rb_t1z: [f32; 4],
    ra_t2x: [f32; 4],
    ra_t2y: [f32; 4],
    ra_t2z: [f32; 4],
    rb_t2x: [f32; 4],
    rb_t2y: [f32; 4],
    rb_t2z: [f32; 4],
    // Scalar constants per lane
    inv_ma: [f32; 4],
    inv_mb: [f32; 4],
    total_inv: [f32; 4],
    inv_k_n: [f32; 4],
    inv_k_t1: [f32; 4],
    inv_k_t2: [f32; 4],
    // Linear application factors: n * inv_mass
    apply_n_ax: [f32; 4],
    apply_n_ay: [f32; 4],
    apply_n_az: [f32; 4],
    apply_n_bx: [f32; 4],
    apply_n_by: [f32; 4],
    apply_n_bz: [f32; 4],
    // Angular application factors: I⁻¹_world · (ra×n)  (precomputed)
    apply_w_ax: [f32; 4],
    apply_w_ay: [f32; 4],
    apply_w_az: [f32; 4],
    apply_w_bx: [f32; 4],
    apply_w_by: [f32; 4],
    apply_w_bz: [f32; 4],
    // World-space inverse inertia matrix rows (3 rows × 2 bodies)
    w_a00: [f32; 4],
    w_a01: [f32; 4],
    w_a02: [f32; 4],
    w_a10: [f32; 4],
    w_a11: [f32; 4],
    w_a12: [f32; 4],
    w_a20: [f32; 4],
    w_a21: [f32; 4],
    w_a22: [f32; 4],
    w_b00: [f32; 4],
    w_b01: [f32; 4],
    w_b02: [f32; 4],
    w_b10: [f32; 4],
    w_b11: [f32; 4],
    w_b12: [f32; 4],
    w_b20: [f32; 4],
    w_b21: [f32; 4],
    w_b22: [f32; 4],
    // Restitution bias, speculative target, friction coeff
    bias: [f32; 4],
    // `target` is a reserved WGSL keyword — the member is named `spec_target`.
    spec_target: [f32; 4],
    mu: [f32; 4],
    // Body indices
    body_a: [u32; 4],
    body_b: [u32; 4],
    // Accumulators (read-write on GPU)
    /// Accumulated normal impulse per lane.
    pub acc: [f32; 4],
    pub(crate) acc_f1: [f32; 4],
    pub(crate) acc_f2: [f32; 4],
    // Active lane count
    /// Active lane count.
    pub count: u32,
    // Explicit tail padding: keeps the struct a multiple of its 16-byte
    // alignment (WGSL stride) without implicit padding, which `Pod` rejects.
    _pad0: u32,
    _pad1: u32,
    _pad2: u32,
}

/// One lane's worth of CPU-side contact data for `GpuBatch::fill_lane`
/// (mirrors the WGSL batch layout: one scalar per field).
pub struct LaneInput<'a> {
    /// Lane index within the batch (0..4).
    pub lane: usize,
    /// Contact normal (body A to body B).
    pub n: Vec3,
    /// Contact offset from body A's center.
    pub ra: Vec3,
    /// Contact offset from body B's center.
    pub rb: Vec3,
    /// Approach-speed target for the lane.
    pub target: f32,
    /// Coulomb friction coefficient.
    pub mu: f32,
    /// Restitution bias.
    pub bias: f32,
    /// Incoming accumulated normal impulse (warm start).
    pub acc_in: f32,
    /// Body A snapshot.
    pub a: &'a RigidBody,
    /// Body A index.
    pub ba_idx: u32,
    /// Body B snapshot.
    pub b: &'a RigidBody,
    /// Body B index.
    pub bb_idx: u32,
}

impl GpuBatch {
    /// Blank batch: zeroed lanes, zero active count.
    pub fn zero() -> Self {
        Self::zeroed()
    }

    /// Fill one lane from CPU-side contact data.
    /// The per-lane scalars are packed into `LaneInput` (which mirrors the
    /// WGSL batch layout: one scalar per field) to stay within the structural
    /// gate's argument-count limit.
    pub fn fill_lane(&mut self, input: LaneInput<'_>) {
        let LaneInput {
            lane,
            n,
            ra,
            rb,
            target,
            mu,
            bias,
            acc_in,
            a,
            ba_idx,
            b,
            bb_idx,
        } = input;
        let l3 = |x: &mut [f32; BATCH_LANES],
                  y: &mut [f32; BATCH_LANES],
                  z: &mut [f32; BATCH_LANES],
                  v: Vec3| {
            x[lane] = v.x;
            y[lane] = v.y;
            z[lane] = v.z;
        };

        l3(&mut self.nx, &mut self.ny, &mut self.nz, n);
        l3(&mut self.rax, &mut self.ray, &mut self.raz, ra);
        l3(&mut self.rbx, &mut self.rby, &mut self.rbz, rb);
        self.spec_target[lane] = target;
        self.mu[lane] = mu;
        self.bias[lane] = bias;
        self.acc[lane] = acc_in;
        self.body_a[lane] = ba_idx;
        self.body_b[lane] = bb_idx;
        self.inv_ma[lane] = a.inv_mass;
        self.inv_mb[lane] = b.inv_mass;
        self.total_inv[lane] = a.inv_mass + b.inv_mass;

        // Precompute cross products.
        let ra_n = ra.cross(n);
        let rb_n = rb.cross(n);
        l3(&mut self.ra_nx, &mut self.ra_ny, &mut self.ra_nz, ra_n);
        l3(&mut self.rb_nx, &mut self.rb_ny, &mut self.rb_nz, rb_n);

        // Tangent basis.
        let t1 = crate::math::tangent_basis(n).0;
        let t2 = t1.cross(n);
        l3(&mut self.t1x, &mut self.t1y, &mut self.t1z, t1);
        l3(&mut self.t2x, &mut self.t2y, &mut self.t2z, t2);
        l3(
            &mut self.ra_t1x,
            &mut self.ra_t1y,
            &mut self.ra_t1z,
            ra.cross(t1),
        );
        l3(
            &mut self.rb_t1x,
            &mut self.rb_t1y,
            &mut self.rb_t1z,
            rb.cross(t1),
        );
        l3(
            &mut self.ra_t2x,
            &mut self.ra_t2y,
            &mut self.ra_t2z,
            ra.cross(t2),
        );
        l3(
            &mut self.rb_t2x,
            &mut self.rb_t2y,
            &mut self.rb_t2z,
            rb.cross(t2),
        );

        // World-space inverse inertia matrix rows + application factors.
        let wa = world_inertia_matrix(a.orientation, a.inertia);
        let wb = world_inertia_matrix(b.orientation, b.inertia);
        let set_mat =
            |m: &[Vec3; LINEAR_DOF], dest: &mut [&mut [f32; BATCH_LANES]; INERTIA_MAT_ELEMS]| {
                for r in 0..LINEAR_DOF {
                    dest[r * LINEAR_DOF][lane] = m[r].x;
                    dest[r * LINEAR_DOF + 1][lane] = m[r].y;
                    dest[r * LINEAR_DOF + 2][lane] = m[r].z;
                }
            };
        set_mat(
            &wa,
            &mut [
                &mut self.w_a00,
                &mut self.w_a01,
                &mut self.w_a02,
                &mut self.w_a10,
                &mut self.w_a11,
                &mut self.w_a12,
                &mut self.w_a20,
                &mut self.w_a21,
                &mut self.w_a22,
            ],
        );
        set_mat(
            &wb,
            &mut [
                &mut self.w_b00,
                &mut self.w_b01,
                &mut self.w_b02,
                &mut self.w_b10,
                &mut self.w_b11,
                &mut self.w_b12,
                &mut self.w_b20,
                &mut self.w_b21,
                &mut self.w_b22,
            ],
        );

        // Application factors.
        l3(
            &mut self.apply_n_ax,
            &mut self.apply_n_ay,
            &mut self.apply_n_az,
            n * a.inv_mass,
        );
        l3(
            &mut self.apply_n_bx,
            &mut self.apply_n_by,
            &mut self.apply_n_bz,
            n * b.inv_mass,
        );
        l3(
            &mut self.apply_w_ax,
            &mut self.apply_w_ay,
            &mut self.apply_w_az,
            matvec(&wa, ra_n),
        );
        l3(
            &mut self.apply_w_bx,
            &mut self.apply_w_by,
            &mut self.apply_w_bz,
            matvec(&wb, rb_n),
        );

        // Effective stiffness inverses.
        let total = a.inv_mass + b.inv_mass;
        let k_n = total + ra_n.dot(matvec(&wa, ra_n)) + rb_n.dot(matvec(&wb, rb_n));
        let k_t1 = total
            + ra.cross(t1).dot(matvec(&wa, ra.cross(t1)))
            + rb.cross(t1).dot(matvec(&wb, rb.cross(t1)));
        let k_t2 = total
            + ra.cross(t2).dot(matvec(&wa, ra.cross(t2)))
            + rb.cross(t2).dot(matvec(&wb, rb.cross(t2)));
        self.inv_k_n[lane] = if k_n >= STIFFNESS_EPS {
            1.0 / k_n
        } else {
            0.0
        };
        self.inv_k_t1[lane] = if k_t1 >= STIFFNESS_EPS {
            1.0 / k_t1
        } else {
            0.0
        };
        self.inv_k_t2[lane] = if k_t2 >= STIFFNESS_EPS {
            1.0 / k_t2
        } else {
            0.0
        };
    }
}
/// World inverse inertia as `[row0, row1, row2]` (3 Vec3 columns → row-major).
fn world_inertia_matrix(rot: glam::Quat, inertia: Vec3) -> [Vec3; LINEAR_DOF] {
    let inv = Vec3::new(
        if inertia.x > 0.0 {
            1.0 / inertia.x
        } else {
            0.0
        },
        if inertia.y > 0.0 {
            1.0 / inertia.y
        } else {
            0.0
        },
        if inertia.z > 0.0 {
            1.0 / inertia.z
        } else {
            0.0
        },
    );
    let m = glam::Mat3::from_quat(rot);
    let col_x = m.x_axis * inv.x;
    let col_y = m.y_axis * inv.y;
    let col_z = m.z_axis * inv.z;
    [
        m.x_axis * col_x.x + m.y_axis * col_y.x + m.z_axis * col_z.x,
        m.x_axis * col_x.y + m.y_axis * col_y.y + m.z_axis * col_z.y,
        m.x_axis * col_x.z + m.y_axis * col_y.z + m.z_axis * col_z.z,
    ]
}

#[inline]
fn matvec(m: &[Vec3; 3], v: Vec3) -> Vec3 {
    Vec3::new(m[0].dot(v), m[1].dot(v), m[2].dot(v))
}
// ---------------------------------------------------------------------------
// Compute shader — written in Rust, translated to WGSL by #[gpu_pipeline]
// ---------------------------------------------------------------------------

/// One iteration of the wide contact solver for a single batch.
///
/// The body of this function is the WGSL compute entry point (kernel DSL):
/// the bindings below are in scope as storage/uniform variables and `gid`/
/// `lid` are the built-in workgroup parameters. The isotropic contact row
/// (normal update, friction clamp) is NOT duplicated here: it calls the
/// shared `contact_math` kernels stitched via `helpers(...)` — one source
/// of truth with the CPU wide/scalar paths. Only buffer plumbing (gather,
/// accumulator read/write, body write-back) stays inline: bindings and
/// builtins are entry-scoped and cannot live in helpers. All per-lane
/// writes to `batch_buf` accumulators go through the full buffer path so
/// that they persist across dispatches (the `let b = ...` copy is
/// read-only).
//
// qual:allow(abc) — kernel-DSL body: every statement is translated
// verbatim into the WGSL compute shader by #[gpu_pipeline], which embeds
// ONLY this function's body into `fn main`. The isotropic row calls the
// shared helpers stitched via `helpers(...)` (see `contact_math`); the
// remaining size is entry-scoped buffer plumbing that cannot move.
#[gpu_pipeline(
    workgroup_size = 4,
    storage(body_buf: [GpuBodyState; 64], read_write),
    storage(batch_buf: [GpuBatch; 64], read_write),
    uniform(params: [u32; 4]),
    builtin(gid: workgroup_id, lid: local_invocation_id),
    helpers(contact_normal_step, contact_friction_clamp),
)]
fn contact_solver() {
    // qual:allow(abc) — kernel-DSL body (see the item docs above): buffer
    // plumbing stays inline, the contact row calls the stitched helpers.
    let b = batch_buf[gid.x];
    let l = lid.x;
    if l >= b.count {
        return;
    }
    let iter = params.x;
    let total = params.y;
    let allow_rest = params.z;

    // Gather body velocities.
    let mut ba = body_buf[b.body_a[l]];
    let mut bb = body_buf[b.body_b[l]];
    let va = ba.velocity;
    let wa = ba.angular;
    let vb = bb.velocity;
    let wb = bb.angular;

    let n = vec3(b.nx[l], b.ny[l], b.nz[l]);
    let ra = vec3(b.rax[l], b.ray[l], b.raz[l]);
    let rb = vec3(b.rbx[l], b.rby[l], b.rbz[l]);
    let inv_ma = b.inv_ma[l];
    let inv_mb = b.inv_mb[l];
    let inv_k = b.inv_k_n[l];
    let spec_target = b.spec_target[l];
    let mut acc = batch_buf[gid.x].acc[l];

    // Normal impulse: shared isotropic row (contact_math).
    let rel = (vb + cross(wb, rb)) - (va + cross(wa, ra));
    let vn = dot(rel, n);
    let new_acc = contact_normal_step(vn, spec_target, inv_k, acc);
    let delta = new_acc - acc;
    acc = new_acc;

    if abs(delta) > 1e-12 {
        ba.velocity -= delta * vec3(b.apply_n_ax[l], b.apply_n_ay[l], b.apply_n_az[l]);
        bb.velocity += delta * vec3(b.apply_n_bx[l], b.apply_n_by[l], b.apply_n_bz[l]);
        ba.angular -= delta * vec3(b.apply_w_ax[l], b.apply_w_ay[l], b.apply_w_az[l]);
        bb.angular += delta * vec3(b.apply_w_bx[l], b.apply_w_by[l], b.apply_w_bz[l]);
    }

    // Friction (remeasure rel after the normal impulse): shared circular
    // clamp per axis (contact_math).
    let rel2 = (bb.velocity + cross(bb.angular, rb)) - (ba.velocity + cross(ba.angular, ra));
    let max_f = b.mu[l] * acc;
    let t1 = vec3(b.t1x[l], b.t1y[l], b.t1z[l]);
    let t2 = vec3(b.t2x[l], b.t2y[l], b.t2z[l]);
    let mut f_imp = vec3(0.0);

    // Axis 1.
    if b.inv_k_t1[l] > 0.0 {
        let vt1 = dot(rel2, t1);
        let raw_t1 = batch_buf[gid.x].acc_f1[l] - vt1 * b.inv_k_t1[l];
        let new_t1 = contact_friction_clamp(raw_t1, batch_buf[gid.x].acc_f2[l], max_f);
        f_imp += t1 * (new_t1 - batch_buf[gid.x].acc_f1[l]);
        batch_buf[gid.x].acc_f1[l] = new_t1;
    }
    // Axis 2.
    if b.inv_k_t2[l] > 0.0 {
        let vt2 = dot(rel2, t2);
        let raw_t2 = batch_buf[gid.x].acc_f2[l] - vt2 * b.inv_k_t2[l];
        let new_t2 = contact_friction_clamp(raw_t2, batch_buf[gid.x].acc_f1[l], max_f);
        f_imp += t2 * (new_t2 - batch_buf[gid.x].acc_f2[l]);
        batch_buf[gid.x].acc_f2[l] = new_t2;
    }
    if dot(f_imp, f_imp) > 1e-24 {
        // Angular impulse uses r × f (same convention as the scalar solver:
        // `wa -= W·(ra×f)`, `wb += W·(rb×f)`).
        let ca = cross(ra, f_imp);
        let w_a = vec3(
            dot(vec3(b.w_a00[l], b.w_a01[l], b.w_a02[l]), ca),
            dot(vec3(b.w_a10[l], b.w_a11[l], b.w_a12[l]), ca),
            dot(vec3(b.w_a20[l], b.w_a21[l], b.w_a22[l]), ca),
        );
        let cb = cross(rb, f_imp);
        let w_b = vec3(
            dot(vec3(b.w_b00[l], b.w_b01[l], b.w_b02[l]), cb),
            dot(vec3(b.w_b10[l], b.w_b11[l], b.w_b12[l]), cb),
            dot(vec3(b.w_b20[l], b.w_b21[l], b.w_b22[l]), cb),
        );
        ba.velocity -= f_imp * inv_ma;
        bb.velocity += f_imp * inv_mb;
        ba.angular -= w_a;
        bb.angular += w_b;
    }

    // Restitution (one-shot on the last iteration).
    if allow_rest > 0 && iter == total - 1 {
        let bias = b.bias[l];
        if bias > 0.0 {
            let rel3 =
                (bb.velocity + cross(bb.angular, rb)) - (ba.velocity + cross(ba.angular, ra));
            let vn3 = dot(rel3, n);
            let lr = (bias - vn3) * inv_k;
            if lr > 0.0 {
                ba.velocity -= lr * vec3(b.apply_n_ax[l], b.apply_n_ay[l], b.apply_n_az[l]);
                bb.velocity += lr * vec3(b.apply_n_bx[l], b.apply_n_by[l], b.apply_n_bz[l]);
                ba.angular -= lr * vec3(b.apply_w_ax[l], b.apply_w_ay[l], b.apply_w_az[l]);
                bb.angular += lr * vec3(b.apply_w_bx[l], b.apply_w_by[l], b.apply_w_bz[l]);
            }
        }
    }

    // Write back.
    body_buf[b.body_a[l]].velocity = ba.velocity;
    body_buf[b.body_a[l]].angular = ba.angular;
    body_buf[b.body_b[l]].velocity = bb.velocity;
    body_buf[b.body_b[l]].angular = bb.angular;
    batch_buf[gid.x].acc[l] = acc;
}

/// The complete WGSL source: struct declarations (generated from the Rust
/// layouts) + the compute shader translated from `contact_solver`.
pub fn contact_solver_wgsl() -> String {
    format!(
        "{}\n{}\n{}",
        GpuBodyState::WGSL_SOURCE,
        GpuBatch::WGSL_SOURCE,
        contact_solver::wgsl_source()
    )
}
// ---------------------------------------------------------------------------
// Public API: pack GPU batches from engine data
// ---------------------------------------------------------------------------

/// Pack single-point manifold states into GPU batches.
/// Returns the batches and their count.
pub fn pack_single_point_batches(
    bodies: &[RigidBody],
    states: &[ManifoldState],
    manifolds: &[Manifold],
    single_indices: &[usize], // indices into states
) -> (Vec<GpuBatch>, u32) {
    // Group into batches of ≤4 disjoint contacts (same strategy as
    // build_solver_steps, but using global body indices).
    let mut batches: Vec<GpuBatch> = Vec::new();
    let mut cur = GpuBatch::zero();
    let mut cur_len = 0usize;
    let mut cur_bodies: [usize; BATCH_BODY_SLOTS] = [usize::MAX; BATCH_BODY_SLOTS];
    let mut cur_n = 0usize;

    fn flush_batch(
        batches: &mut Vec<GpuBatch>,
        cur: &mut GpuBatch,
        cur_len: &mut usize,
        cur_bodies: &mut [usize; BATCH_BODY_SLOTS],
        cur_n: &mut usize,
    ) {
        if *cur_len == 0 {
            return;
        }
        cur.count = *cur_len as u32;
        batches.push(*cur);
        *cur = GpuBatch::zero();
        *cur_len = 0;
        *cur_n = 0;
        *cur_bodies = [usize::MAX; BATCH_BODY_SLOTS];
    }

    for &si in single_indices {
        let st = &states[si];
        let m = &manifolds[st.mi];
        let (i, j) = (st.i, st.j);
        let conflicts = cur_bodies[..cur_n].contains(&i) || cur_bodies[..cur_n].contains(&j);
        if cur_len >= BATCH_LANES || conflicts {
            flush_batch(
                &mut batches,
                &mut cur,
                &mut cur_len,
                &mut cur_bodies,
                &mut cur_n,
            );
        }
        let p = m.points[0].world_point;
        let ra = p - bodies[i].position;
        let rb = p - bodies[j].position;
        cur.fill_lane(LaneInput {
            lane: cur_len,
            n: m.normal,
            ra,
            rb,
            target: st.target[0],
            mu: st.mu,
            bias: st.bias[0],
            acc_in: st.acc[0],
            a: &bodies[i],
            ba_idx: i as u32,
            b: &bodies[j],
            bb_idx: j as u32,
        });
        cur_bodies[cur_n] = i;
        cur_bodies[cur_n + 1] = j;
        cur_n += 2;
        cur_len += 1;
        cur.count = cur_len as u32;
    }
    flush_batch(
        &mut batches,
        &mut cur,
        &mut cur_len,
        &mut cur_bodies,
        &mut cur_n,
    );

    let count = batches.len() as u32;
    (batches, count)
}

/// Write GPU batch accumulated impulses back to the ManifoldState array
/// (for warm-cache persistence).
pub fn write_back_acc(
    states: &mut [ManifoldState],
    single_indices: &[usize],
    batches: &[GpuBatch],
) {
    let mut bi = 0usize;
    let mut lane = 0usize;
    for &si in single_indices {
        if lane >= batches[bi].count as usize {
            bi += 1;
            lane = 0;
        }
        states[si].acc[0] = batches[bi].acc[lane];
        lane += 1;
    }
}
