[package]
name = "ornis-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
editor-backend = { path = "../editor-backend" }
ornis-animation = { path = "../animation" }
ornis-assets = { path = "../assets" }
ornis-audio = { path = "../audio" }
ornis-core = { path = "../core" }
ornis-editor = { path = "../editor" }
ornis-gameplay = { path = "../gameplay" }
ornis-gltf = { path = "../gltf" }
ornis-physics = { path = "../physics" }
ornis-render = { path = "../render" }
crossbeam-channel = "0.5"
glam = "0.34"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0"

[lints]
workspace = true
