[package]
name = "ornis-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
editor-backend = { path = "../editor-backend", version = "0.1.0" }
ornis-animation = { path = "../animation", version = "0.1.0" }
ornis-assets = { path = "../assets", version = "0.1.0" }
ornis-audio = { path = "../audio", version = "0.1.0" }
ornis-core = { path = "../core", version = "0.1.0" }
ornis-editor = { path = "../editor", version = "0.1.0" }
ornis-gameplay = { path = "../gameplay", version = "0.1.0" }
ornis-gltf = { path = "../gltf", version = "0.1.0" }
ornis-physics = { path = "../physics", version = "0.1.0" }
ornis-render = { path = "../render", version = "0.1.0" }
crossbeam-channel = "0.5"
glam = "0.34"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0"

[lints]
workspace = true
