[package]
name = "ornis-gameplay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ornis-core = { path = "../core" }
ornis-input = { path = "../input" }
ornis-macros = { path = "../macros" }
glam = "0.33"
serde = "1.0"

[lints]
workspace = true
