[package]
name = "ornis-gameplay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ornis-core = { path = "../core", version = "0.1.0" }
ornis-input = { path = "../input", version = "0.1.0" }
ornis-macros = { path = "../macros", version = "0.1.0" }
glam = "0.34"
serde = "1.0"

[lints]
workspace = true
