[package]
name = "ornis-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ornis-app = { path = "../app", version = "0.1.0" }
ornis-core = { path = "../core", version = "0.1.0" }
ornis-render = { path = "../render", version = "0.1.0" }
crossbeam-channel = "0.5"
editor-backend = { path = "../editor-backend", version = "0.1.0" }
pollster = "1.0"
wgpu = "30"
winit = "0.30"

[lints]
workspace = true
