[package]
name = "ornis-animation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ornis-assets = { path = "../assets" }
ornis-core = { path = "../core" }
ornis-gameplay = { path = "../gameplay" }
glam = "0.33"

[dev-dependencies]
ornis-render = { path = "../render" }

[lints]
workspace = true
