[package]
name = "ornis-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rayon = "1.10"
fixedbitset = "0.5"
crossbeam-channel = "0.5"
glam = "0.30"

[dependencies.crossbeam-epoch]
version = "0.9"
optional = true

[features]
default = []
lock-free = ["crossbeam-epoch"]

[dev-dependencies]
criterion = { version = "0.5", features = ["rayon"] }
ornis-macros = { path = "../macros" }

[[bench]]
name = "store_bench"
harness = false

[[bench]]
name = "comparison_bench"
harness = false
