[package]
name = "ornis-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rayon = "1.10"
fixedbitset = "0.5"
crossbeam-channel = "0.5"
crossbeam-epoch = "0.9"
glam = "0.30"

[features]
default = []

[dev-dependencies]
criterion = { version = "0.5", features = ["rayon"] }
bytemuck = { version = "1.25", features = ["derive"] }
ornis-macros = { path = "../macros" }

[[bench]]
name = "store_bench"
harness = false

[[bench]]
name = "comparison_bench"
harness = false
