//! Ornis core ECS: entities, component storage, scheduling, and the
//! CPU/GPU dispatch layer.
//!
//! The crate provides the data backbone of the engine: [`Entity`] handles
//! with generational reuse, dense ([`ComponentStore`]) and packed
//! ([`SmartStore`]) component storage, a dependency-driven [`Schedule`],
//! and a [`Dispatcher`] that routes work between CPU lanes and GPU compute.
//! [`Engine`] adds a backend-neutral frame boundary with [`Time`] and
//! [`InputState`] resources over the logical [`World`]. The [`material`]
//! module holds the GPU-ready OpenPBR material layout.
#![warn(missing_docs)]

mod cold_store;
mod command_sync;
mod component_store;
mod dispatcher;
mod engine;
mod entity;
mod input;
#[cfg(feature = "lock-free")]
mod lock_free_store;
pub mod material;
mod page_table;
/// Compile-time CPU/GPU routing for the smart pipeline.
pub mod pipeline;
mod prefetch;
mod registry;
pub mod schedule;
mod smart_store;
mod world;

pub use cold_store::ColdComponentStore;
pub use command_sync::{
    CommandQueue, CommandSync, CommandSyncable, DataResidency, GpuCommand, ResidencyTracker,
};
pub use component_store::{ChunkedIterMut, ComponentStore, ZipIter};
pub use dispatcher::{CpuExecutor, Dispatchable, Dispatcher, ExecutionTarget, SmartDispatcher};
pub use engine::{Engine, Time};
pub use entity::{Entity, EntityAllocator};
pub use input::InputState;
pub use material::{OPENPBR_MATERIAL_SIZE, OPENPBR_MATERIAL_VEC4_COUNT, OpenPBRMaterial};
pub use page_table::{PAGE_SIZE, PageTable};
pub use pipeline::{
    AutoPipeline, CpuLane, GpuLane, HybridLane, LaneTarget, PipelineConfig, Route,
    TargetDiscriminant, lane_target_of, pipeline_enter, pipeline_exit,
};
pub use prefetch::prefetch_read;
// Re-exported so code generated by `ornis_macros::smart_pipeline` can refer to
// Rayon traits without requiring the caller crate to depend on rayon directly.
pub use rayon;
pub use registry::{ComponentMeta, ComponentRegistry, LaneId, RegistryError};
pub use schedule::{OrderError, Resources, Schedule, System, SystemAccess, compute_levels};
pub use smart_store::{Pack, SmartStore};
pub use world::World;
