//! Ornis core ECS: entities, component storage, scheduling, and the
//! CPU/GPU dispatch layer.
//!
//! The crate provides the data backbone of the engine: [`Entity`] handles
//! with generational reuse, dense ([`ComponentStore`]) and packed
//! ([`SmartStore`]) component storage, a dependency-driven [`Schedule`],
//! and a [`Dispatcher`] that decides CPU-vs-GPU placement by element count
//! (execution itself lives in backend crates).
//! [`Engine`] adds a backend-neutral frame boundary with [`Time`],
//! [`FixedTime`] and [`InputState`] resources over the logical [`World`].
//! The [`material`]
//! module holds the GPU-ready OpenPBR material layout.
#![warn(missing_docs)]

mod cold_store;
mod command_sync;
mod component_store;
mod dispatcher;
mod engine;
mod entity;
/// Stable scalar wrappers for GPU-compatible buffer representations.
pub mod gpu_types;
/// Parent links, local [`Transform`], and world [`GlobalTransform`].
pub mod hierarchy;
#[cfg(feature = "lock-free")]
mod lock_free_store;
pub mod material;
/// World mutation bus: the single write protocol for world content.
pub mod mutation;
mod page_table;
/// Compile-time CPU/GPU routing for the smart pipeline.
pub mod pipeline;
mod prefetch;
mod registry;
pub mod schedule;
mod smart_store;
/// Phantom build/run phases and scalar newtypes for the frame boundary.
pub mod typestate;
/// Physical and rendering unit newtypes over raw `f32` soup.
pub mod units;
mod world;

pub use cold_store::ColdComponentStore;
pub use command_sync::{
    CommandQueue, CommandSync, CommandSyncable, DataResidency, GpuCommand, ResidencyTracker,
};
pub use component_store::{ChunkedIterMut, ComponentStore, ZipIter};
pub use dispatcher::{CpuExecutor, Dispatchable, Dispatcher, ExecutionTarget, SmartDispatcher};
pub use engine::{
    DEFAULT_FIXED_DELTA_SECONDS, DEFAULT_MAX_FIXED_STEPS_PER_FRAME, Engine, EngineBuilder,
    FixedTime, Stage, Time,
};
pub use entity::{DenseIndex, Entity, EntityAllocator, EntityId, Generation};
pub use gpu_types::GpuBool;
pub use hierarchy::{
    ChildOf, Children, GlobalTransform, HierarchyError, Name, PropagateTransforms, Transform,
    clear_parent, despawn_recursive, install_fixed_transform_propagation,
    install_transform_propagation, propagate_registered, propagate_transforms, reconcile_children,
    set_parent,
};
pub use material::{OPENPBR_MATERIAL_SIZE, OPENPBR_MATERIAL_VEC4_COUNT, OpenPBRMaterial};
/// Backend-neutral input (re-exported from `ornis-input` so downstream
/// crates keep a single import path: adapters write raw codes, gameplay
/// reads through [`InputMap`] or named keys).
pub use ornis_input::{InputBinding, InputMap, InputState, KeyCode, MouseButton};
pub use page_table::{PAGE_SIZE, PageTable};
pub use pipeline::{
    AutoPipeline, CpuLane, GpuLane, HybridLane, LaneTarget, PipelineConfig, Route,
    TargetDiscriminant, lane_target_of, pipeline_enter, pipeline_exit,
};
pub use prefetch::prefetch_read;
// Re-exported so code generated by `ornis_macros::smart_pipeline` can refer to
// Rayon traits without requiring the caller crate to depend on rayon directly.
pub use rayon;
pub use registry::{
    ComponentMeta, ComponentName, ComponentRegistry, FieldMeta, FieldPath, FieldPathError,
    FieldSegment, FieldSurface, LaneId, RegisterComponent, RegistryError,
};
pub use schedule::{
    OrderError, Resources, Schedule, System, SystemAccess, SystemName, compute_levels,
};
pub use smart_store::{Pack, SmartStore};
pub use typestate::{
    Authoritative, Building, FixedSteps, Frame, Phase, Replica, Running, SceneEntities, SceneRole,
    SceneVersion, Seconds, Tick,
};
/// Unit newtypes shared by physics, assets, gameplay and render (point 2:
/// `f32`-soup consolidation). [`units::Seconds`] is the frame-boundary
/// [`Seconds`] re-exported, so there is exactly one duration type.
pub use units::{
    Clamped01, Clamped01Error, Color, Degrees, EnvironmentWeight, GearRatio, Hertz, HexColorError,
    Ior, IorError, Kilograms, LinearRgb, LinearRgba, Lux, Metallic, Meters, MetersPerSecond,
    Position, PositiveF32, PositiveF32Error, Radians, RadiansPerSecond, Roughness, SecondsExt,
    Specular, UnitQuat, UnitQuatError, UnitVec3, UnitVec3Error,
};
pub use world::World;
