mod cold_store;
mod command_sync;
mod component_store;
mod dispatcher;
mod entity;
#[cfg(feature = "lock-free")]
mod lock_free_store;
pub mod material;
mod page_table;
pub mod pipeline;
mod prefetch;
pub mod schedule;
mod smart_store;

pub use cold_store::ColdComponentStore;
pub use command_sync::{
    CommandQueue, CommandSync, CommandSyncable, DataResidency, GpuCommand, ResidencyTracker,
};
pub use component_store::{ChunkedIterMut, ComponentStore, ZipIter};
pub use dispatcher::{CpuExecutor, Dispatchable, Dispatcher, ExecutionTarget, SmartDispatcher};
pub use entity::{Entity, EntityAllocator};
pub use material::{OPENPBR_MATERIAL_SIZE, OPENPBR_MATERIAL_VEC4_COUNT, OpenPBRMaterial};
pub use page_table::{PAGE_SIZE, PageTable};
pub use pipeline::{
    AutoPipeline, CpuLane, GpuLane, HybridLane, LaneTarget, PipelineConfig, Route,
    TargetDiscriminant, lane_target_of, pipeline_enter, pipeline_exit,
};
pub use prefetch::prefetch_read;
// Re-exported so code generated by `ornis_macros::smart_pipeline` can refer to
// Rayon traits without requiring the caller crate to depend on rayon directly.
pub use rayon;
pub use schedule::{OrderError, Resources, Schedule, System, SystemAccess, compute_levels};
pub use smart_store::{Pack, SmartStore};
