//! Compile-time lane routing between CPU and GPU executors.
//!
//! ZST markers ([`CpuLane`], [`GpuLane`], [`HybridLane`]) map to a
//! [`TargetDiscriminant`] through the [`Route`] trait; components declare
//! their marker via [`LaneTarget`], so [`lane_target_of`] monomorphizes to
//! a constant with no runtime branch. [`AutoPipeline`] and
//! [`PipelineConfig`] are the traits implemented by the derive macros in
//! `ornis-macros`, with manual impls here for primitive component types.

use crate::smart_store::SmartStore;

/// Result of the static profiler: where to execute the lane.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetDiscriminant {
    /// Execute on CPU threads only.
    Cpu,
    /// Execute on the GPU.
    Gpu,
    /// Split work between CPU and GPU.
    Hybrid,
    /// Decide at runtime using a heuristic threshold.
    Auto(usize),
}

/// Marker for GPU-executable lanes.
pub struct GpuLane;
/// Marker for CPU-only lanes.
pub struct CpuLane;
/// Marker for hybrid CPU/GPU lanes.
pub struct HybridLane;

/// Determines which executor a component lane targets.
pub trait LaneTarget {
    /// The ZST lane marker this component routes through.
    type Target;
}

/// Maps a ZST marker to a [`TargetDiscriminant`] at compile time (zero-cost dispatch).
pub trait Route {
    /// Returns the compile-time target for this lane marker.
    fn platform() -> TargetDiscriminant;
}

impl Route for CpuLane {
    fn platform() -> TargetDiscriminant {
        TargetDiscriminant::Cpu
    }
}

impl Route for GpuLane {
    fn platform() -> TargetDiscriminant {
        TargetDiscriminant::Gpu
    }
}

impl Route for HybridLane {
    fn platform() -> TargetDiscriminant {
        TargetDiscriminant::Hybrid
    }
}

/// Resolve a [`LaneTarget`] to its execution discriminant via ZST dispatch.
/// Monomorphizes to a constant — no runtime branch.
pub fn lane_target_of<T: LaneTarget>() -> TargetDiscriminant
where
    T::Target: Route,
{
    <T::Target as Route>::platform()
}

/// Auto-registration trait generated by `#[derive(AutoPipeline)]`.
pub trait AutoPipeline: Sized + Send + Sync + 'static {
    /// Registers this component type in the store.
    fn register(store: &mut SmartStore);
    /// Name of the lane target ("cpu" or "gpu") for diagnostics.
    fn lane_target() -> &'static str {
        "cpu"
    }
}

// Default implementations for common types so they work without macros.
macro_rules! impl_auto_pipeline {
    ($t:ty) => {
        impl AutoPipeline for $t {
            fn register(store: &mut SmartStore) {
                store.register::<$t>();
            }
        }
    };
}

impl_auto_pipeline!(f32);
impl_auto_pipeline!(u32);
impl_auto_pipeline!(i32);
impl_auto_pipeline!(u64);
impl_auto_pipeline!(f64);

// Manual LaneTarget impls for primitive types that implement AutoPipeline.
impl LaneTarget for f32 {
    type Target = CpuLane;
}
impl LaneTarget for u32 {
    type Target = CpuLane;
}
impl LaneTarget for i32 {
    type Target = CpuLane;
}
impl LaneTarget for u64 {
    type Target = CpuLane;
}
impl LaneTarget for f64 {
    type Target = CpuLane;
}

/// Compile-time profiling trait generated by `#[derive(PipelineConfig)]`.
pub trait PipelineConfig: Sized {
    /// Compile-time execution target chosen by the profiler.
    fn lane_target() -> TargetDiscriminant;
    /// Element count above which the lane is worth offloading.
    const THRESHOLD: usize;
}

/// Hook called when a `#[smart_pipeline]` function enters.
pub fn pipeline_enter() {}

/// Hook called when a `#[smart_pipeline]` function exits.
pub fn pipeline_exit() {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pipeline_hooks_noop() {
        pipeline_enter();
        pipeline_exit();
    }

    #[test]
    fn auto_pipeline_for_primitives() {
        let mut store = crate::SmartStore::new();
        f32::register(&mut store);
        u32::register(&mut store);
    }

    #[test]
    fn auto_pipeline_lane_target_is_cpu() {
        // The default lane target string must remain exactly "cpu":
        // callers match on this literal (mutants replacing it with ""
        // or "xyzzy" would silently change dispatch).
        assert_eq!(<f32 as AutoPipeline>::lane_target(), "cpu");
        assert_eq!(<u32 as AutoPipeline>::lane_target(), "cpu");
    }

    #[test]
    fn lane_target_of_maps_markers() {
        assert_eq!(lane_target_of::<f32>(), TargetDiscriminant::Cpu);
        assert_eq!(lane_target_of::<u64>(), TargetDiscriminant::Cpu);
    }
}
